import "@/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { cn } from "@/lib/utils";
import { getBaseUrl } from "@/trpc/shared";
import { type ReactNode, Suspense } from "react";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  metadataBase: new URL(getBaseUrl()),
  title: "Hype Sneakers",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  robots: {
    follow: true,
    index: true,
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/*suppressHydrationWarning if getting errors*/}
      <body
        className={cn(
          "relative h-full bg-background font-sans antialiased",
          inter.variable,
        )}
      >
        <TRPCReactProvider>
          <Navbar />
          <Suspense>
            <main className="relative flex min-h-screen flex-col">
              <div className="flex-1 flex-grow">{children}</div>
            </main>
            <Toaster />
          </Suspense>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
