revoke delete on table "public"."t3-supabase_post" from "anon";

revoke insert on table "public"."t3-supabase_post" from "anon";

revoke references on table "public"."t3-supabase_post" from "anon";

revoke select on table "public"."t3-supabase_post" from "anon";

revoke trigger on table "public"."t3-supabase_post" from "anon";

revoke truncate on table "public"."t3-supabase_post" from "anon";

revoke update on table "public"."t3-supabase_post" from "anon";

revoke delete on table "public"."t3-supabase_post" from "authenticated";

revoke insert on table "public"."t3-supabase_post" from "authenticated";

revoke references on table "public"."t3-supabase_post" from "authenticated";

revoke select on table "public"."t3-supabase_post" from "authenticated";

revoke trigger on table "public"."t3-supabase_post" from "authenticated";

revoke truncate on table "public"."t3-supabase_post" from "authenticated";

revoke update on table "public"."t3-supabase_post" from "authenticated";

revoke delete on table "public"."t3-supabase_post" from "service_role";

revoke insert on table "public"."t3-supabase_post" from "service_role";

revoke references on table "public"."t3-supabase_post" from "service_role";

revoke select on table "public"."t3-supabase_post" from "service_role";

revoke trigger on table "public"."t3-supabase_post" from "service_role";

revoke truncate on table "public"."t3-supabase_post" from "service_role";

revoke update on table "public"."t3-supabase_post" from "service_role";

alter table "public"."t3-supabase_post" drop constraint "t3-supabase_post_pkey";

drop index if exists "public"."name_idx";

drop index if exists "public"."t3-supabase_post_pkey";

drop table "public"."t3-supabase_post";

create table "public"."addresses" (
    "id" bigint generated by default as identity not null,
    "user_id" bigint,
    "title" character varying,
    "address_line_1" character varying,
    "address_line_2" character varying,
    "country" character varying,
    "city" character varying,
    "postal_code" character varying,
    "phone_number" character varying,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."addresses" enable row level security;

create table "public"."cart" (
    "id" bigint generated by default as identity not null,
    "user_id" bigint,
    "total" bigint,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
);


alter table "public"."cart" enable row level security;

create table "public"."cart_item" (
    "id" bigint generated by default as identity not null,
    "cart_id" bigint,
    "product_id" bigint,
    "products_sku_id" bigint,
    "quantity" bigint,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
);


alter table "public"."cart_item" enable row level security;

create table "public"."categories" (
    "id" bigint generated by default as identity not null,
    "name" character varying,
    "description" character varying,
    "created_at" timestamp with time zone not null default now(),
    "deleted_at" timestamp with time zone
);


alter table "public"."categories" enable row level security;

create table "public"."order_details" (
    "id" bigint generated by default as identity not null,
    "user_id" bigint,
    "payment_id" bigint,
    "total" bigint,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
);


alter table "public"."order_details" enable row level security;

create table "public"."order_item" (
    "id" bigint generated by default as identity not null,
    "order_id" bigint,
    "product_id" bigint,
    "products_sku_id" bigint,
    "quantity" bigint,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
);


alter table "public"."order_item" enable row level security;

create table "public"."payment_details" (
    "id" bigint generated by default as identity not null,
    "order_id" bigint,
    "amount" bigint,
    "provider" character varying,
    "status" character varying,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
);


alter table "public"."payment_details" enable row level security;

create table "public"."product_ attributes" (
    "id" bigint generated by default as identity not null,
    "type" character varying,
    "value" character varying,
    "created_at" timestamp with time zone not null default now(),
    "deleted_at" timestamp with time zone
);


alter table "public"."product_ attributes" enable row level security;

create table "public"."products" (
    "id" bigint generated by default as identity not null,
    "name" character varying,
    "description" character varying,
    "color" character varying,
    "sku" character varying,
    "price" character varying,
    "category_id" bigint,
    "deleted_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."products" enable row level security;

create table "public"."products_skus" (
    "id" bigint generated by default as identity not null,
    "product_id" bigint,
    "size_attribute_id" bigint,
    "color_attribute_id" bigint,
    "sku" character varying,
    "price" character varying,
    "quantity" bigint,
    "created_at" timestamp with time zone not null default now(),
    "deleted_at" timestamp with time zone
);


alter table "public"."products_skus" enable row level security;

create table "public"."sub_categories" (
    "id" bigint generated by default as identity not null,
    "parent_id" bigint,
    "name" character varying,
    "description" character varying,
    "created_at" timestamp with time zone not null default now(),
    "deleted_at" timestamp with time zone
);


alter table "public"."sub_categories" enable row level security;

create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "avatar" character varying,
    "first_name" character varying,
    "last_name" character varying,
    "username" character varying not null,
    "email" character varying not null,
    "password" character varying,
    "date_of_birth" date,
    "phone_number" character varying,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."users" enable row level security;

create table "public"."wishlist" (
    "id" bigint generated by default as identity not null,
    "product_id" bigint,
    "user_id" bigint,
    "created_at" timestamp with time zone not null default now(),
    "deleted_at" timestamp with time zone
);


alter table "public"."wishlist" enable row level security;

drop sequence if exists "public"."t3-supabase_post_id_seq";

CREATE UNIQUE INDEX addresses_pkey ON public.addresses USING btree (id);

CREATE UNIQUE INDEX cart_item_pkey ON public.cart_item USING btree (id);

CREATE UNIQUE INDEX cart_pkey ON public.cart USING btree (id);

CREATE UNIQUE INDEX categories_pkey ON public.categories USING btree (id);

CREATE UNIQUE INDEX order_details_pkey ON public.order_details USING btree (id);

CREATE UNIQUE INDEX order_item_pkey ON public.order_item USING btree (id);

CREATE UNIQUE INDEX payment_details_pkey ON public.payment_details USING btree (id);

CREATE UNIQUE INDEX "product_ attributes_pkey" ON public."product_ attributes" USING btree (id);

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);

CREATE UNIQUE INDEX products_skus_pkey ON public.products_skus USING btree (id);

CREATE UNIQUE INDEX sub_categories_pkey ON public.sub_categories USING btree (id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

CREATE UNIQUE INDEX wishlist_pkey ON public.wishlist USING btree (id);

alter table "public"."addresses" add constraint "addresses_pkey" PRIMARY KEY using index "addresses_pkey";

alter table "public"."cart" add constraint "cart_pkey" PRIMARY KEY using index "cart_pkey";

alter table "public"."cart_item" add constraint "cart_item_pkey" PRIMARY KEY using index "cart_item_pkey";

alter table "public"."categories" add constraint "categories_pkey" PRIMARY KEY using index "categories_pkey";

alter table "public"."order_details" add constraint "order_details_pkey" PRIMARY KEY using index "order_details_pkey";

alter table "public"."order_item" add constraint "order_item_pkey" PRIMARY KEY using index "order_item_pkey";

alter table "public"."payment_details" add constraint "payment_details_pkey" PRIMARY KEY using index "payment_details_pkey";

alter table "public"."product_ attributes" add constraint "product_ attributes_pkey" PRIMARY KEY using index "product_ attributes_pkey";

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."products_skus" add constraint "products_skus_pkey" PRIMARY KEY using index "products_skus_pkey";

alter table "public"."sub_categories" add constraint "sub_categories_pkey" PRIMARY KEY using index "sub_categories_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."wishlist" add constraint "wishlist_pkey" PRIMARY KEY using index "wishlist_pkey";

alter table "public"."addresses" add constraint "addresses_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."addresses" validate constraint "addresses_user_id_fkey";

alter table "public"."products" add constraint "products_category_id_fkey" FOREIGN KEY (category_id) REFERENCES categories(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."products" validate constraint "products_category_id_fkey";

alter table "public"."sub_categories" add constraint "sub_categories_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES categories(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."sub_categories" validate constraint "sub_categories_parent_id_fkey";

grant delete on table "public"."addresses" to "anon";

grant insert on table "public"."addresses" to "anon";

grant references on table "public"."addresses" to "anon";

grant select on table "public"."addresses" to "anon";

grant trigger on table "public"."addresses" to "anon";

grant truncate on table "public"."addresses" to "anon";

grant update on table "public"."addresses" to "anon";

grant delete on table "public"."addresses" to "authenticated";

grant insert on table "public"."addresses" to "authenticated";

grant references on table "public"."addresses" to "authenticated";

grant select on table "public"."addresses" to "authenticated";

grant trigger on table "public"."addresses" to "authenticated";

grant truncate on table "public"."addresses" to "authenticated";

grant update on table "public"."addresses" to "authenticated";

grant delete on table "public"."addresses" to "service_role";

grant insert on table "public"."addresses" to "service_role";

grant references on table "public"."addresses" to "service_role";

grant select on table "public"."addresses" to "service_role";

grant trigger on table "public"."addresses" to "service_role";

grant truncate on table "public"."addresses" to "service_role";

grant update on table "public"."addresses" to "service_role";

grant delete on table "public"."cart" to "anon";

grant insert on table "public"."cart" to "anon";

grant references on table "public"."cart" to "anon";

grant select on table "public"."cart" to "anon";

grant trigger on table "public"."cart" to "anon";

grant truncate on table "public"."cart" to "anon";

grant update on table "public"."cart" to "anon";

grant delete on table "public"."cart" to "authenticated";

grant insert on table "public"."cart" to "authenticated";

grant references on table "public"."cart" to "authenticated";

grant select on table "public"."cart" to "authenticated";

grant trigger on table "public"."cart" to "authenticated";

grant truncate on table "public"."cart" to "authenticated";

grant update on table "public"."cart" to "authenticated";

grant delete on table "public"."cart" to "service_role";

grant insert on table "public"."cart" to "service_role";

grant references on table "public"."cart" to "service_role";

grant select on table "public"."cart" to "service_role";

grant trigger on table "public"."cart" to "service_role";

grant truncate on table "public"."cart" to "service_role";

grant update on table "public"."cart" to "service_role";

grant delete on table "public"."cart_item" to "anon";

grant insert on table "public"."cart_item" to "anon";

grant references on table "public"."cart_item" to "anon";

grant select on table "public"."cart_item" to "anon";

grant trigger on table "public"."cart_item" to "anon";

grant truncate on table "public"."cart_item" to "anon";

grant update on table "public"."cart_item" to "anon";

grant delete on table "public"."cart_item" to "authenticated";

grant insert on table "public"."cart_item" to "authenticated";

grant references on table "public"."cart_item" to "authenticated";

grant select on table "public"."cart_item" to "authenticated";

grant trigger on table "public"."cart_item" to "authenticated";

grant truncate on table "public"."cart_item" to "authenticated";

grant update on table "public"."cart_item" to "authenticated";

grant delete on table "public"."cart_item" to "service_role";

grant insert on table "public"."cart_item" to "service_role";

grant references on table "public"."cart_item" to "service_role";

grant select on table "public"."cart_item" to "service_role";

grant trigger on table "public"."cart_item" to "service_role";

grant truncate on table "public"."cart_item" to "service_role";

grant update on table "public"."cart_item" to "service_role";

grant delete on table "public"."categories" to "anon";

grant insert on table "public"."categories" to "anon";

grant references on table "public"."categories" to "anon";

grant select on table "public"."categories" to "anon";

grant trigger on table "public"."categories" to "anon";

grant truncate on table "public"."categories" to "anon";

grant update on table "public"."categories" to "anon";

grant delete on table "public"."categories" to "authenticated";

grant insert on table "public"."categories" to "authenticated";

grant references on table "public"."categories" to "authenticated";

grant select on table "public"."categories" to "authenticated";

grant trigger on table "public"."categories" to "authenticated";

grant truncate on table "public"."categories" to "authenticated";

grant update on table "public"."categories" to "authenticated";

grant delete on table "public"."categories" to "service_role";

grant insert on table "public"."categories" to "service_role";

grant references on table "public"."categories" to "service_role";

grant select on table "public"."categories" to "service_role";

grant trigger on table "public"."categories" to "service_role";

grant truncate on table "public"."categories" to "service_role";

grant update on table "public"."categories" to "service_role";

grant delete on table "public"."order_details" to "anon";

grant insert on table "public"."order_details" to "anon";

grant references on table "public"."order_details" to "anon";

grant select on table "public"."order_details" to "anon";

grant trigger on table "public"."order_details" to "anon";

grant truncate on table "public"."order_details" to "anon";

grant update on table "public"."order_details" to "anon";

grant delete on table "public"."order_details" to "authenticated";

grant insert on table "public"."order_details" to "authenticated";

grant references on table "public"."order_details" to "authenticated";

grant select on table "public"."order_details" to "authenticated";

grant trigger on table "public"."order_details" to "authenticated";

grant truncate on table "public"."order_details" to "authenticated";

grant update on table "public"."order_details" to "authenticated";

grant delete on table "public"."order_details" to "service_role";

grant insert on table "public"."order_details" to "service_role";

grant references on table "public"."order_details" to "service_role";

grant select on table "public"."order_details" to "service_role";

grant trigger on table "public"."order_details" to "service_role";

grant truncate on table "public"."order_details" to "service_role";

grant update on table "public"."order_details" to "service_role";

grant delete on table "public"."order_item" to "anon";

grant insert on table "public"."order_item" to "anon";

grant references on table "public"."order_item" to "anon";

grant select on table "public"."order_item" to "anon";

grant trigger on table "public"."order_item" to "anon";

grant truncate on table "public"."order_item" to "anon";

grant update on table "public"."order_item" to "anon";

grant delete on table "public"."order_item" to "authenticated";

grant insert on table "public"."order_item" to "authenticated";

grant references on table "public"."order_item" to "authenticated";

grant select on table "public"."order_item" to "authenticated";

grant trigger on table "public"."order_item" to "authenticated";

grant truncate on table "public"."order_item" to "authenticated";

grant update on table "public"."order_item" to "authenticated";

grant delete on table "public"."order_item" to "service_role";

grant insert on table "public"."order_item" to "service_role";

grant references on table "public"."order_item" to "service_role";

grant select on table "public"."order_item" to "service_role";

grant trigger on table "public"."order_item" to "service_role";

grant truncate on table "public"."order_item" to "service_role";

grant update on table "public"."order_item" to "service_role";

grant delete on table "public"."payment_details" to "anon";

grant insert on table "public"."payment_details" to "anon";

grant references on table "public"."payment_details" to "anon";

grant select on table "public"."payment_details" to "anon";

grant trigger on table "public"."payment_details" to "anon";

grant truncate on table "public"."payment_details" to "anon";

grant update on table "public"."payment_details" to "anon";

grant delete on table "public"."payment_details" to "authenticated";

grant insert on table "public"."payment_details" to "authenticated";

grant references on table "public"."payment_details" to "authenticated";

grant select on table "public"."payment_details" to "authenticated";

grant trigger on table "public"."payment_details" to "authenticated";

grant truncate on table "public"."payment_details" to "authenticated";

grant update on table "public"."payment_details" to "authenticated";

grant delete on table "public"."payment_details" to "service_role";

grant insert on table "public"."payment_details" to "service_role";

grant references on table "public"."payment_details" to "service_role";

grant select on table "public"."payment_details" to "service_role";

grant trigger on table "public"."payment_details" to "service_role";

grant truncate on table "public"."payment_details" to "service_role";

grant update on table "public"."payment_details" to "service_role";

grant delete on table "public"."product_ attributes" to "anon";

grant insert on table "public"."product_ attributes" to "anon";

grant references on table "public"."product_ attributes" to "anon";

grant select on table "public"."product_ attributes" to "anon";

grant trigger on table "public"."product_ attributes" to "anon";

grant truncate on table "public"."product_ attributes" to "anon";

grant update on table "public"."product_ attributes" to "anon";

grant delete on table "public"."product_ attributes" to "authenticated";

grant insert on table "public"."product_ attributes" to "authenticated";

grant references on table "public"."product_ attributes" to "authenticated";

grant select on table "public"."product_ attributes" to "authenticated";

grant trigger on table "public"."product_ attributes" to "authenticated";

grant truncate on table "public"."product_ attributes" to "authenticated";

grant update on table "public"."product_ attributes" to "authenticated";

grant delete on table "public"."product_ attributes" to "service_role";

grant insert on table "public"."product_ attributes" to "service_role";

grant references on table "public"."product_ attributes" to "service_role";

grant select on table "public"."product_ attributes" to "service_role";

grant trigger on table "public"."product_ attributes" to "service_role";

grant truncate on table "public"."product_ attributes" to "service_role";

grant update on table "public"."product_ attributes" to "service_role";

grant delete on table "public"."products" to "anon";

grant insert on table "public"."products" to "anon";

grant references on table "public"."products" to "anon";

grant select on table "public"."products" to "anon";

grant trigger on table "public"."products" to "anon";

grant truncate on table "public"."products" to "anon";

grant update on table "public"."products" to "anon";

grant delete on table "public"."products" to "authenticated";

grant insert on table "public"."products" to "authenticated";

grant references on table "public"."products" to "authenticated";

grant select on table "public"."products" to "authenticated";

grant trigger on table "public"."products" to "authenticated";

grant truncate on table "public"."products" to "authenticated";

grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "service_role";

grant insert on table "public"."products" to "service_role";

grant references on table "public"."products" to "service_role";

grant select on table "public"."products" to "service_role";

grant trigger on table "public"."products" to "service_role";

grant truncate on table "public"."products" to "service_role";

grant update on table "public"."products" to "service_role";

grant delete on table "public"."products_skus" to "anon";

grant insert on table "public"."products_skus" to "anon";

grant references on table "public"."products_skus" to "anon";

grant select on table "public"."products_skus" to "anon";

grant trigger on table "public"."products_skus" to "anon";

grant truncate on table "public"."products_skus" to "anon";

grant update on table "public"."products_skus" to "anon";

grant delete on table "public"."products_skus" to "authenticated";

grant insert on table "public"."products_skus" to "authenticated";

grant references on table "public"."products_skus" to "authenticated";

grant select on table "public"."products_skus" to "authenticated";

grant trigger on table "public"."products_skus" to "authenticated";

grant truncate on table "public"."products_skus" to "authenticated";

grant update on table "public"."products_skus" to "authenticated";

grant delete on table "public"."products_skus" to "service_role";

grant insert on table "public"."products_skus" to "service_role";

grant references on table "public"."products_skus" to "service_role";

grant select on table "public"."products_skus" to "service_role";

grant trigger on table "public"."products_skus" to "service_role";

grant truncate on table "public"."products_skus" to "service_role";

grant update on table "public"."products_skus" to "service_role";

grant delete on table "public"."sub_categories" to "anon";

grant insert on table "public"."sub_categories" to "anon";

grant references on table "public"."sub_categories" to "anon";

grant select on table "public"."sub_categories" to "anon";

grant trigger on table "public"."sub_categories" to "anon";

grant truncate on table "public"."sub_categories" to "anon";

grant update on table "public"."sub_categories" to "anon";

grant delete on table "public"."sub_categories" to "authenticated";

grant insert on table "public"."sub_categories" to "authenticated";

grant references on table "public"."sub_categories" to "authenticated";

grant select on table "public"."sub_categories" to "authenticated";

grant trigger on table "public"."sub_categories" to "authenticated";

grant truncate on table "public"."sub_categories" to "authenticated";

grant update on table "public"."sub_categories" to "authenticated";

grant delete on table "public"."sub_categories" to "service_role";

grant insert on table "public"."sub_categories" to "service_role";

grant references on table "public"."sub_categories" to "service_role";

grant select on table "public"."sub_categories" to "service_role";

grant trigger on table "public"."sub_categories" to "service_role";

grant truncate on table "public"."sub_categories" to "service_role";

grant update on table "public"."sub_categories" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";

grant delete on table "public"."wishlist" to "anon";

grant insert on table "public"."wishlist" to "anon";

grant references on table "public"."wishlist" to "anon";

grant select on table "public"."wishlist" to "anon";

grant trigger on table "public"."wishlist" to "anon";

grant truncate on table "public"."wishlist" to "anon";

grant update on table "public"."wishlist" to "anon";

grant delete on table "public"."wishlist" to "authenticated";

grant insert on table "public"."wishlist" to "authenticated";

grant references on table "public"."wishlist" to "authenticated";

grant select on table "public"."wishlist" to "authenticated";

grant trigger on table "public"."wishlist" to "authenticated";

grant truncate on table "public"."wishlist" to "authenticated";

grant update on table "public"."wishlist" to "authenticated";

grant delete on table "public"."wishlist" to "service_role";

grant insert on table "public"."wishlist" to "service_role";

grant references on table "public"."wishlist" to "service_role";

grant select on table "public"."wishlist" to "service_role";

grant trigger on table "public"."wishlist" to "service_role";

grant truncate on table "public"."wishlist" to "service_role";

grant update on table "public"."wishlist" to "service_role";


